# Generated by Django 2.0.4 on 2018-05-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name_plural': '商品表'},
        ),
        migrations.AlterModelOptions(
            name='gtype',
            options={'verbose_name_plural': '商品类型'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='gimage',
            field=models.ImageField(upload_to='static/df_goods'),
        ),
    ]
