# Generated by Django 2.0.4 on 2018-05-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=10)),
                ('upassword', models.CharField(max_length=50)),
                ('uemail', models.CharField(max_length=20)),
                ('uphone', models.BigIntegerField(max_length=11)),
                ('usname', models.CharField(max_length=20, null=True)),
                ('uaddress', models.CharField(max_length=60, null=True)),
                ('uregister_time', models.TimeField()),
            ],
        ),
    ]
