# Generated by Django 2.0.4 on 2018-05-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_auto_20180513_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uphone',
            field=models.BigIntegerField(null=True),
        ),
    ]
