# Generated by Django 2.0.4 on 2018-05-13 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0002_auto_20180513_0124'),
        ('reg', '0003_auto_20180513_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(max_length=10)),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.User')),
            ],
            options={
                'verbose_name_plural': '购物车表',
            },
        ),
    ]
